### ISSUE TITLE
In the develop branch, layout AppLayout.Style.css

### ISSUE THREAD

**Issue by MayHyeyeonKim** [ExploreX-App/ExploreX#6]
layout 폴더에
- `AppLayout.Style.css`
- `AppLayout.style.css`
가 충돌나고 있습니다.

`AppLayout.Style.css`로 통일해서 쓰는 게 좋을 것 같습니다.

**Comment by amy-em-ahn** [comment]
안녕하세요~
AppLayout.Style.css가 제가 처음에 셋팅해뒀던거고 그 이후에는 손대지 않았어요.
이따 회의때 이 부분도 이야기 해야겠네요.
알려주셔서 감사합니다~ ^^

2024년 9월 10일 (화) 오후 1:28, MayHyeyeonKim ***@***.***>님이 작성:
